name: audio_ebook_sync
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as 9*versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.6+16

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #new_version: ^0.3.1
  purchases_flutter: ^3.10.0
  facebook_app_events: ^0.18.3

  sizer: ^2.0.15
  searchable_listview: ^2.2.1
  translator: ^0.1.7
  html: ^0.15.1
  in_app_review: ^2.0.6
  google_speech: ^2.0.1
  google_ml_kit: ^0.11.0
 # in_app_purchase: ^3.0.5
  epubx: ^3.0.0
  change_app_package_name: ^1.0.0
  flutter_ffmpeg: ^0.4.2
 # ffmpeg_kit_flutter: ^5.1.0
  path_provider: ^2.0.9
  sensors_plus: ^1.3.1
 # flutter_tesseract_ocr: ^0.4.19
  image_picker: ^0.8.5
  flutter_ringtone_player: ^3.2.0
  async: ^2.10.0
  flutter_email_sender: ^5.2.0
  loader_overlay: ^2.1.0









  file_picker: ^4.0.0
  just_audio: ^0.9.7
  #assets_audio_player: ^3.0.3+6
  # syncfusion_flutter_pdfviewer: ^20.1.52-beta
  #syncfusion_flutter_pdf: ^20.1.52-beta
 # syncfusion_flutter_pdfviewer: ^19.2.59-beta
  syncfusion_flutter_pdfviewer: ^20.1.60-beta
  syncfusion_flutter_pdf: ^20.1.60-beta
  #syncfusion_flutter_pdf: ^19.4.56-beta
 # ffmpeg_kit_flutter: ^4.5.1
  #flutter_ffmpeg:
  #   path: ./flutter_ffmpeg_changed/
 # pdf_text:
#    path: ./flutter-pdf-text-dev/
  text_selection_controls:
    path: ./text_selection_controls/


  shared_preferences: ^2.0.7
 # pdf_text: ^0.5.0



  http: ^0.13.3
  flutter_bloc: ^7.3.0
  flutter_spinkit: ^5.1.0
  just_audio_background: ^0.0.1-beta.1
  audioplayers: ^0.20.1
  audio_service: ^0.18.1
  wakelock: ^0.6.0+1
  fluttertoast: ^8.0.9
  flutter_statusbarcolor_ns: ^0.5.0






  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/applogo6.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
